// ============================================================
// PINORATOR ARCADE 3D — Blender-built cabinet + live HTML screen.
// pinocab.glb is generated by make_arcade.py (Blender headless);
// its 'monitor' plane hosts the CRT UI as a CSS3DObject, and the
// art_* planes are runtime texture slots. script.js untouched.
// ============================================================
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { CSS3DRenderer, CSS3DObject } from 'three/addons/renderers/CSS3DRenderer.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

// ================= SUAS TEXTURAS AQUI =================
// Coloque imagens (png/jpg) no projeto e aponte o caminho.
// Deixe null para usar o visual padrao ($PINO branco/amarelo).
const TEXTURES = {
  side: null,     // arte lateral (os dois lados)     ex.: 'images/arcade/side.png'
  marquee: null,  // letreiro do topo                 ex.: 'images/arcade/marquee.png'
  front: null,    // painel frontal (coin door)       ex.: 'images/arcade/front.png'
  deck: null,     // superficie do painel de controle ex.: 'images/arcade/deck.png'
};
// ======================================================

const ROOM_COLOR = 0x05030c;
// world width of the monitor glass in px; the .crt element is authored
// wider (880px, see arcade3d.css) and shrunk to fit — free supersampling
const UI_WIDTH = 640;
const REDUCED = matchMedia('(prefers-reduced-motion: reduce)').matches;

const webglRoot = document.getElementById('webgl-root');
const cssRoot = document.getElementById('css3d-root');
const crtEl = document.querySelector('.crt');

// the action buttons join the screen UI, like an in-game menu
crtEl.querySelector('.customization').after(document.getElementById('buttons-container'));

// as miniaturas dos outfits herdam o background selecionado no preview
// (cores > aesthetic > fundo padrao); apresentacao pura via observer
function syncThumbBackgrounds() {
  const disp = document.getElementById('avatar-display');
  const bg = disp.querySelector('#cores-layer')
    || disp.querySelector('#based-layer')
    || disp.querySelector('#background-layer');
  const src = bg ? bg.getAttribute('src') : 'images/default/default_background.png';
  const sel = '.options.front button, .options.hats button, .options.glasses button, ' +
    '.options.clothes button, .options.mouth button';
  for (const btn of document.querySelectorAll(sel)) {
    btn.style.backgroundImage = `url("images/default/default_pino.png"), url("${src}")`;
    btn.style.backgroundSize = 'cover, cover';
    btn.style.backgroundPosition = 'center, center';
  }
}
new MutationObserver(syncThumbBackgrounds).observe(
  document.getElementById('avatar-display'),
  { childList: true, subtree: true, attributes: true, attributeFilter: ['src'] }
);
syncThumbBackgrounds();

const scene = new THREE.Scene();
// transparent canvas: the room paints opaque pixels, the monitor mesh
// punches a hole for the DOM screen underneath
scene.fog = new THREE.Fog(ROOM_COLOR, 700, 4200);

const cssScene = new THREE.Scene();

const camera = new THREE.PerspectiveCamera(40, innerWidth / innerHeight, 1, 14000);

const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
renderer.setClearColor(0x000000, 0);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.setSize(innerWidth, innerHeight);
webglRoot.appendChild(renderer.domElement);

const cssRenderer = new CSS3DRenderer();
cssRenderer.setSize(innerWidth, innerHeight);
cssRoot.appendChild(cssRenderer.domElement);

// nada pode rolar o container do mundo CSS3D (scrollIntoView, foco etc.)
for (const el of [cssRenderer.domElement, cssRoot]) {
  el.addEventListener('scroll', () => {
    el.scrollLeft = 0;
    el.scrollTop = 0;
  });
}

// UI events must not leak into the camera controls on document.body;
// tocar no menu tambem pausa o carrossel automatico
let lastMenuTouch = 0;
let carouselDir = 1;
for (const type of ['pointerdown', 'wheel']) {
  cssRoot.addEventListener(type, ev => {
    ev.stopPropagation();
    lastMenuTouch = clock.elapsedTime;
  });
}

const screenObj = new CSS3DObject(crtEl);
cssScene.add(screenObj);

// gate registered BEFORE OrbitControls: when a press lands on the
// machine's controls, the event never reaches the camera
let gatePointerDown = null;
document.body.addEventListener('pointerdown', ev => {
  if (gatePointerDown && gatePointerDown(ev)) ev.stopImmediatePropagation();
});

const controls = new OrbitControls(camera, document.body);
controls.enableDamping = true;
controls.dampingFactor = 0.06;
controls.enablePan = false;
controls.minAzimuthAngle = -0.6;
controls.maxAzimuthAngle = 0.6;
controls.minPolarAngle = Math.PI / 2 - 0.6;
controls.maxPolarAngle = Math.PI / 2 + 0.15;

// ---------- texture helpers ----------
const texLoader = new THREE.TextureLoader();

function imageTexture(path) {
  const t = texLoader.load(path);
  t.colorSpace = THREE.SRGBColorSpace;
  t.anisotropy = 4;
  return t;
}

function neonTexture(text, color, px = 90, bg = '#160d2a', blur = 42) {
  const c = document.createElement('canvas');
  c.width = 1024; c.height = 256;
  const x = c.getContext('2d');
  if (bg) {
    x.fillStyle = bg;
    x.fillRect(0, 0, 1024, 256);
  }
  x.font = `${px}px "Press Start 2P", monospace`;
  x.textAlign = 'center';
  x.textBaseline = 'middle';
  if (blur > 0) {
    x.shadowColor = color;
    x.shadowBlur = blur;
  }
  x.fillStyle = color;
  for (let i = 0; i < (blur > 0 ? 4 : 1); i++) x.fillText(text, 512, 134);
  const t = new THREE.CanvasTexture(c);
  t.colorSpace = THREE.SRGBColorSpace;
  return t;
}

// ---------- room ----------
const flickering = [];

function addSign(text, color, x, y, z, ry = 0, scale = 1) {
  const mat = new THREE.MeshBasicMaterial({
    map: neonTexture(text, color, 90, null),
    transparent: true,
    opacity: 0, // todos os letreiros nascem desligados; a intro os acende
    depthWrite: false,
    fog: false,
  });
  const m = new THREE.Mesh(new THREE.PlaneGeometry(760 * scale, 190 * scale), mat);
  m.position.set(x, y, z);
  m.rotation.y = ry;
  m.userData.base = 0.8 + Math.random() * 0.2;
  m.userData.seed = Math.random() * 100;
  m.userData.powerAt = Infinity;
  flickering.push(m);
  scene.add(m);
}

function buildRoom(floorY) {
  const floor = new THREE.Mesh(
    new THREE.PlaneGeometry(10000, 10000),
    new THREE.MeshStandardMaterial({ color: 0x0a0616, roughness: 0.35, metalness: 0.55 })
  );
  floor.rotation.x = -Math.PI / 2;
  floor.position.y = floorY;
  floor.receiveShadow = true;
  scene.add(floor);

  const grid = new THREE.GridHelper(10000, 100, 0x2ee6ff, 0x2ee6ff);
  grid.material.transparent = true;
  grid.material.opacity = 0.16;
  grid.position.y = floorY + 2;
  scene.add(grid);

  const backWall = new THREE.Mesh(
    new THREE.PlaneGeometry(10000, 4600),
    new THREE.MeshStandardMaterial({ color: 0x0b0618, roughness: 0.95 })
  );
  backWall.position.set(0, floorY + 2300, -2600);
  scene.add(backWall);

  addSign('$PINO', '#f7ca16', -1050, 700, -2500, 0.12, 1.5);
  addSign('WAGMI', '#2ee6ff', 1100, 850, -2520, -0.1, 1);
  addSign('DEGEN', '#39ff6a', 1250, 180, -2540, -0.06, 0.9);
  addSign('HODL', '#ff6300', -1250, 90, -2540, 0.08, 0.9);
  addSign('GM', '#ff3ea5', -1650, 420, -1750, 0.5, 0.8);
  addSign('TO THE MOON', '#8f7bd8', 1700, 470, -1650, -0.5, 0.7);
}

let screenGlowLight = null;

function buildLights(h) {
  // late-night room: almost no ambient, one lamp over the machine,
  // and the screen itself as the main light source
  scene.add(new THREE.AmbientLight(0x8f86c0, 0.16));

  const spot = new THREE.SpotLight(0xfff3e0, 2.6, 0, 0.5, 0.7, 0);
  spot.position.set(80, h * 0.7 + 700, 500);
  spot.target.position.set(0, -h * 0.12, 60);
  spot.castShadow = true;
  spot.shadow.mapSize.set(2048, 2048);
  spot.shadow.bias = -0.0004;
  spot.shadow.camera.near = 200;
  spot.shadow.camera.far = 7000;
  scene.add(spot, spot.target);

  screenGlowLight = new THREE.PointLight(0x39ff6a, 1.15, 0, 0);
  screenGlowLight.position.set(0, 40, 340);
  scene.add(screenGlowLight);

  const magenta = new THREE.PointLight(0xff3ea5, 0.2, 0, 0);
  magenta.position.set(-1400, 300, -1000);
  scene.add(magenta);

  const cyan = new THREE.PointLight(0x2ee6ff, 0.2, 0, 0);
  cyan.position.set(1400, 300, -1000);
  scene.add(cyan);
}

// ---------- the machine, generated in Blender ----------
async function loadCabinet() {
  const gltf = await new GLTFLoader().loadAsync('pinocab.glb');
  const model = gltf.scene;
  scene.add(model);

  // botoes, joystick e gabinete projetam e recebem sombra do spot
  model.traverse(o => {
    if (o.isMesh) {
      o.castShadow = o.name !== 'monitor';
      o.receiveShadow = true;
    }
  });

  // runtime texture slots: user image, default art, or hidden
  const artMap = {
    art_side_l: TEXTURES.side,
    art_side_r: TEXTURES.side,
    art_marquee: TEXTURES.marquee,
    art_front: TEXTURES.front,
    art_deck: TEXTURES.deck,
  };
  model.traverse(o => {
    if (!o.isMesh || !(o.name in artMap)) return;
    const path = artMap[o.name];
    if (path) {
      o.material = new THREE.MeshBasicMaterial({ map: imageTexture(path), transparent: true });
    } else if (o.name === 'art_marquee') {
      o.material = new THREE.MeshBasicMaterial({
        map: neonTexture('PINORATOR', '#f7ca16', 96, '#000000', 0),
        transparent: true,
        opacity: 0, // acende junto com o boot da tela
      });
      o.userData.base = 1;
      o.userData.seed = 7;
      o.userData.powerAt = Infinity;
      flickering.push(o);
    } else {
      o.visible = false;
    }
  });

  const monitor = model.getObjectByName('monitor');

  // depth-only "hole": the canvas stays transparent where the glass is,
  // revealing the DOM screen below, while still occluding the interior
  monitor.material = new THREE.MeshBasicMaterial({ colorWrite: false });
  monitor.renderOrder = -1;

  // scale the machine so the monitor glass is UI_WIDTH world px wide
  model.updateMatrixWorld(true);
  let box = new THREE.Box3().setFromObject(monitor);
  let size = box.getSize(new THREE.Vector3());
  model.scale.setScalar(UI_WIDTH / size.x);
  model.updateMatrixWorld(true);

  // center the monitor at the origin
  box = new THREE.Box3().setFromObject(monitor);
  size = box.getSize(new THREE.Vector3());
  model.position.sub(box.getCenter(new THREE.Vector3()));
  model.updateMatrixWorld(true);

  // orient the UI to the monitor's tilt: the surface rises from its
  // front-bottom edge (max z) to its back-top edge (min z)
  const upDir = new THREE.Vector3(0, size.y, -size.z).normalize();
  const rightDir = new THREE.Vector3(1, 0, 0);
  const normalDir = new THREE.Vector3().crossVectors(rightDir, upDir).normalize();
  screenObj.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(rightDir, upDir, normalDir));
  screenObj.position.copy(normalDir).multiplyScalar(8);

  return { model, monLen: Math.hypot(size.y, size.z) };
}

// ---------- physical controls: real buttons + working joystick ----------
const DOM_BTN = { btn_0: 'generate-btn', btn_1: 'default-btn', btn_2: 'download-btn' };
const BTN_LABELS = {
  btn_0: ['PINOMIZE', '#f7ca16'],
  btn_1: ['RESET', '#ff3ea5'],
  btn_2: ['DOWNLOAD', '#39ff6a'],
};
const TAB_IDS = ['tab-front', 'tab-hats', 'tab-eyes', 'tab-clothes', 'tab-mouth', 'tab-cores', 'tab-based'];
const TAB_OPTS = {
  'tab-front': 'front', 'tab-hats': 'hats', 'tab-eyes': 'glasses',
  'tab-clothes': 'clothes', 'tab-mouth': 'mouth', 'tab-cores': 'cores', 'tab-based': 'based',
};
const traitIndex = {};
const pressables = [];
const btnRest = new Map();
const lampFor = new Map();
let cabinetModel = null;
let pressDirLocal = new THREE.Vector3(0, 0, -1);
let joyPivot = null;
const joyTilt = new THREE.Vector2(); // target x (frente/tras), y (lados)
let joyDrag = null;

function labelTexture(text, color) {
  // texto solido, sem glow — legibilidade acima de tudo
  const c = document.createElement('canvas');
  c.width = 512; c.height = 96;
  const x = c.getContext('2d');
  x.font = '52px "Press Start 2P", monospace';
  x.textAlign = 'center';
  x.textBaseline = 'middle';
  x.fillStyle = '#0d0d0d';
  x.fillText(text, 256, 50);
  const t = new THREE.CanvasTexture(c);
  t.colorSpace = THREE.SRGBColorSpace;
  t.anisotropy = 8;
  return t;
}

function activeTabId() {
  return TAB_IDS.find(id => document.getElementById(id).checked);
}

function switchTab(dir) {
  const i = TAB_IDS.indexOf(activeTabId());
  document.getElementById(TAB_IDS[(i + dir + TAB_IDS.length) % TAB_IDS.length]).click();
}

function navTrait(dir) {
  const cls = TAB_OPTS[activeTabId()];
  const btns = [...document.querySelectorAll(`.options.${cls} button`)];
  if (!btns.length) return;
  const next = ((traitIndex[cls] ?? 0) + dir + btns.length) % btns.length;
  traitIndex[cls] = next;
  lastMenuTouch = clock.elapsedTime;
  const b = btns[next];
  b.click();
  // rola SOMENTE o slider — scrollIntoView rolaria os containers do
  // CSS3DRenderer e deslocaria a tela inteira dentro do furo
  const slider = b.closest('.slider');
  if (slider) {
    slider.scrollTo({
      left: (b.offsetLeft - slider.offsetLeft) - slider.clientWidth / 2 + b.offsetWidth / 2,
      behavior: 'smooth',
    });
  }
  btns.forEach(x => x.classList.remove('joy-selected'));
  b.classList.add('joy-selected');
}

let joyFrenzyUntil = -1;

function tabFrenzy() {
  // percorre todas as categorias e volta na original; cada categoria
  // entra ja varrendo rapido — um lado, depois o outro, sem parar
  const startIdx = TAB_IDS.indexOf(activeTabId());
  let step = 1;
  const total = TAB_IDS.length;
  const iv = setInterval(() => {
    document.getElementById(TAB_IDS[(startIdx + step) % total]).click();
    const s = [...document.querySelectorAll('.slider')].find(el => el.offsetParent !== null);
    if (s) {
      const max = Math.max(0, s.scrollWidth - s.clientWidth);
      const dir = step % 2;
      s.scrollTo({ left: dir ? 0 : max, behavior: 'instant' });
      s.scrollTo({ left: dir ? max : 0, behavior: 'smooth' });
    }
    step++;
    if (step > total) {
      clearInterval(iv);
      lastMenuTouch = clock.elapsedTime - 1.2; // carrossel retoma rapidinho
    }
  }, 175);
}

function sliderFrenzy() {
  // varredura de slot machine no slider visivel
  const s = [...document.querySelectorAll('.slider')].find(el => el.offsetParent !== null);
  if (!s) return;
  const max = Math.max(0, s.scrollWidth - s.clientWidth);
  s.scrollTo({ left: Math.min(max, s.scrollLeft + 280), behavior: 'smooth' });
  setTimeout(() => s.scrollTo({ left: Math.random() * max, behavior: 'smooth' }), 280);
}

function pressButton(name) {
  const mesh = cabinetModel && cabinetModel.getObjectByName(name);
  if (mesh) {
    mesh.userData.press = 1;
    const lf = lampFor.get(mesh);
    if (lf) lf.lamp.userData.flash = 1; // a lampada acende forte no clique
  }
  if (name !== 'btn_2') {
    // a tela inteira surta: glitch full-screen + frenesi nas miniaturas
    crtEl.classList.add('glitching');
    setTimeout(() => crtEl.classList.remove('glitching'), 1500);
    if (name === 'btn_0') {
      sliderFrenzy();
      tabFrenzy();
      joyFrenzyUntil = clock.elapsedTime + 1.5; // joystick danca junto
    }
    lastMenuTouch = clock.elapsedTime + 1.8; // carrossel espera o surto passar
  }
  if (name === 'btn_0') {
    // caca-niquel: a PFP troca loucamente e para na ultima
    let n = 0;
    const iv = setInterval(() => {
      document.getElementById('generate-btn').click();
      if (++n >= 8) clearInterval(iv);
    }, 165);
  } else {
    setTimeout(() => document.getElementById(DOM_BTN[name]).click(), 70);
  }
}

function setupMachineControls(model) {
  cabinetModel = model;

  for (const name of Object.keys(DOM_BTN)) {
    const m = model.getObjectByName(name);
    if (!m) continue;
    pressables.push(m);
    btnRest.set(m, m.position.clone());
    // a lampada interna afunda junto com o plastico
    const lamp = model.getObjectByName('btn_lamp_' + name.split('_')[1]);
    if (lamp) {
      lampFor.set(m, { lamp, rest: lamp.position.clone(), base: lamp.material.emissiveIntensity || 1 });
    }
  }

  // deck orientation straight from the blueprint: surface drops ~21.8
  // degrees toward the player (world +Z forward, +Y up)
  const DECK_ANG = Math.atan2(0.07, 0.175);
  const outNormal = new THREE.Vector3(0, Math.cos(DECK_ANG), Math.sin(DECK_ANG));
  const downSlope = new THREE.Vector3(0, -Math.sin(DECK_ANG), Math.cos(DECK_ANG));
  const labelQuat = new THREE.Quaternion().setFromRotationMatrix(
    new THREE.Matrix4().makeBasis(new THREE.Vector3(1, 0, 0), downSlope.clone().negate(), outNormal)
  );
  // model root carries no rotation, so world dir == local dir
  pressDirLocal = outNormal.clone().multiplyScalar(-1);

  // engraved labels under the buttons
  for (const [name, [text, color]] of Object.entries(BTN_LABELS)) {
    const m = model.getObjectByName(name);
    if (!m) continue;
    const p = new THREE.Vector3();
    m.getWorldPosition(p);
    const label = new THREE.Mesh(
      new THREE.PlaneGeometry(74, 17),
      new THREE.MeshBasicMaterial({ map: labelTexture(text, color), transparent: true, fog: false })
    );
    label.quaternion.copy(labelQuat);
    label.position.copy(p).addScaledVector(outNormal, 16);
    scene.add(label);
    const bm = model.getObjectByName(name);
    const lf = bm && lampFor.get(bm);
    if (lf) {
      lf.label = label;
      lf.labelRest = label.position.clone();
    }
  }

  // joystick pivot so stick + ball tilt around the base
  const base = model.getObjectByName('joy_base');
  const stick = model.getObjectByName('joy_stick');
  const ball = model.getObjectByName('joy_ball');
  joyPivot = new THREE.Group();
  base.parent.add(joyPivot);
  joyPivot.position.copy(base.position);
  joyPivot.attach(stick);
  joyPivot.attach(ball);

  // alvos de toque generosos (invisiveis) para dedo no celular
  const hitMat = new THREE.MeshBasicMaterial({ transparent: true, opacity: 0, depthWrite: false });
  const joyGrab = new THREE.Mesh(new THREE.SphereGeometry(0.075, 10, 8), hitMat);
  joyGrab.position.copy(ball.position);
  joyPivot.add(joyGrab);

  const btnProxies = [];
  for (const name of Object.keys(DOM_BTN)) {
    const m = model.getObjectByName(name);
    if (!m) continue;
    const proxy = new THREE.Mesh(new THREE.SphereGeometry(0.06, 10, 8), hitMat);
    proxy.position.copy(m.position);
    proxy.userData.btn = name;
    m.parent.add(proxy);
    btnProxies.push(proxy);
  }

  const raycaster = new THREE.Raycaster();
  const pointer = new THREE.Vector2();

  function pick(ev, objects) {
    const r = renderer.domElement.getBoundingClientRect();
    pointer.set(((ev.clientX - r.left) / r.width) * 2 - 1, -((ev.clientY - r.top) / r.height) * 2 + 1);
    raycaster.setFromCamera(pointer, camera);
    return raycaster.intersectObjects(objects, false)[0];
  }

  gatePointerDown = ev => {
    if (intro && !intro.done) {
      finishIntro(); // um toque pula a intro
      return false;
    }
    const hit = pick(ev, [...btnProxies, ...pressables]);
    if (hit) {
      pressButton(hit.object.userData.btn || hit.object.name);
      return true; // consome o evento: a camera nao ve o toque
    }
    if (pick(ev, [joyGrab, ball, stick, base])) {
      joyDrag = { x: ev.clientX, y: ev.clientY, fired: false };
      return true;
    }
    return false;
  };

  addEventListener('pointermove', ev => {
    if (!joyDrag) return;
    const dx = ev.clientX - joyDrag.x;
    const dy = ev.clientY - joyDrag.y;
    joyTilt.set(
      THREE.MathUtils.clamp(dy * 0.008, -0.38, 0.38),
      THREE.MathUtils.clamp(dx * 0.008, -0.38, 0.38)
    );
    const TH = 30;
    if (!joyDrag.fired) {
      if (Math.abs(dx) > TH && Math.abs(dx) >= Math.abs(dy)) {
        navTrait(dx > 0 ? 1 : -1);
        joyDrag.fired = true;
      } else if (Math.abs(dy) > TH) {
        switchTab(dy > 0 ? 1 : -1);
        joyDrag.fired = true;
      }
    } else if (Math.abs(dx) < TH * 0.4 && Math.abs(dy) < TH * 0.4) {
      joyDrag.fired = false; // voltar ao centro rearma o gesto
    }
  });

  addEventListener('pointerup', () => {
    joyDrag = null;
    joyTilt.set(0, 0);
    controls.enabled = !intro || intro.done;
  });

  // keyboard mirrors the joystick: arrows navigate, Enter pinomizes
  addEventListener('keydown', ev => {
    switch (ev.key) {
      case 'ArrowLeft': navTrait(-1); joyKick(0, -1); break;
      case 'ArrowRight': navTrait(1); joyKick(0, 1); break;
      case 'ArrowUp': switchTab(-1); joyKick(-1, 0); break;
      case 'ArrowDown': switchTab(1); joyKick(1, 0); break;
      case 'Enter': pressButton('btn_0'); break;
      default: return;
    }
    ev.preventDefault();
  });
}

let joyKickTimer = null;
function joyKick(x, y) {
  joyTilt.set(x * 0.3, y * 0.3);
  clearTimeout(joyKickTimer);
  joyKickTimer = setTimeout(() => joyTilt.set(0, 0), 180);
}

// ---------- intro sequence ----------
let intro = null;

// pose final do jogador: enquadra dos botoes ao topo da tela em
// qualquer proporcao de janela (retrato incluso)
function playerPose() {
  const normal = new THREE.Vector3(0, 0, 1).applyQuaternion(screenObj.quaternion);
  const tanV = Math.tan(THREE.MathUtils.degToRad(camera.fov / 2));
  let target, dist;
  let lift;
  if (camera.aspect < 0.9) {
    // retrato: o vidro do jogo preenche a largura do telefone (as
    // laterais do gabinete cortam) e a base fica presa nos botoes
    dist = 262 / (tanV * camera.aspect);
    // mira no centro da PFP (parte alta da tela), camera bem elevada
    target = new THREE.Vector3(0, -20, 40);
    lift = 460;
  } else {
    const halfH = 335;
    const halfW = 335;
    dist = Math.max(halfH / tanV, halfW / (tanV * camera.aspect));
    target = new THREE.Vector3(0, -30, 40);
    lift = 260;
  }
  const pos = target.clone().addScaledVector(normal, dist).add(new THREE.Vector3(0, lift, 0));
  return { pos, target };
}

function powerOnSigns(baseT) {
  flickering.forEach((m, i) => { m.userData.powerAt = baseT + i * 0.24; });
}

function finishIntro() {
  if (!intro || intro.done) return;
  intro.done = true;
  camera.position.copy(intro.finalPos);
  controls.target.copy(intro.frameCenter);
  controls.enabled = true;
  powerOnSigns(clock.elapsedTime);
}

// ---------- boot ----------
async function init() {
  try {
    await Promise.race([
      Promise.all([document.fonts.load('16px "Press Start 2P"'), document.fonts.ready]),
      new Promise(r => setTimeout(r, 2500)),
    ]);
  } catch { /* fonts are cosmetic; the scene still builds */ }

  const { model, monLen } = await loadCabinet();

  // first CSS render mounts the element; then it can be measured
  cssRenderer.render(cssScene, camera);
  document.querySelector('.cabinet').style.display = 'none';
  // fill the whole glass: per-axis scale (the UI layout is tuned to the
  // glass aspect, so the residual stretch is a few percent, invisible)
  const uiW = crtEl.offsetWidth || UI_WIDTH;
  const uiH = crtEl.offsetHeight || 900;
  screenObj.scale.set(UI_WIDTH / uiW, monLen / uiH, 1);

  const mBox = new THREE.Box3().setFromObject(model);
  const mSize = mBox.getSize(new THREE.Vector3());

  buildRoom(mBox.min.y);
  buildLights(mSize.y);

  // ---- intro: dark empty room, CRT boots, camera flies to the player
  // pose aligned with the screen plane (framing deck + screen top) ----
  const pose = playerPose();
  const finalPos = pose.pos;
  const frameCenter = pose.target;
  const startPos = new THREE.Vector3(0, mSize.y * 0.28, 4300);

  controls.minDistance = 480;
  controls.maxDistance = 3400;
  controls.enabled = false;

  intro = {
    t0: null,
    dur: 3.4,
    startPos,
    finalPos,
    startTarget: new THREE.Vector3(0, 60, 0),
    frameCenter,
    done: false,
  };

  if (REDUCED) {
    intro.done = true;
    camera.position.copy(finalPos);
    controls.target.copy(frameCenter);
    controls.enabled = true;
    powerOnSigns(0);
  } else {
    camera.position.copy(startPos);
    controls.target.copy(intro.startTarget);
    camera.lookAt(intro.startTarget);
  }
  controls.update();
  controls.enabled = intro.done;

  setupMachineControls(model);

  renderer.setAnimationLoop(tick);
  tick(); // paint the first frame synchronously, even in a throttled tab
}

const clock = new THREE.Clock();

function tick() {
  const dt = clock.getDelta();
  const t = clock.elapsedTime;

  if (intro && !intro.done) {
    if (intro.t0 === null) {
      intro.t0 = t;
      // os neons acendem em cascata quando a camera esta chegando
      powerOnSigns(t + intro.dur * 0.55);
    }
    const k = Math.min(1, (t - intro.t0) / intro.dur);
    const e = k < 0.5 ? 4 * k * k * k : 1 - Math.pow(-2 * k + 2, 3) / 2;
    camera.position.lerpVectors(intro.startPos, intro.finalPos, e);
    controls.target.lerpVectors(intro.startTarget, intro.frameCenter, e);
    camera.lookAt(controls.target);
    if (k >= 1) {
      intro.done = true;
      controls.enabled = true;
    }
  } else {
    controls.update();
  }

  // carrosseis em modo atracao: a fileira visivel gira sozinha
  if (!REDUCED && (!intro || intro.done) && t - lastMenuTouch > 1.6) {
    const s = [...document.querySelectorAll('.slider')].find(el => el.offsetParent !== null);
    if (s) {
      const max = s.scrollWidth - s.clientWidth;
      if (max > 4) {
        let x = s.scrollLeft + carouselDir * dt * 55;
        if (x >= max) { x = max; carouselDir = -1; }
        else if (x <= 0) { x = 0; carouselDir = 1; }
        s.scrollTo({ left: x, behavior: 'instant' });
      }
    }
  }

  // a tela e a fonte de luz da sala: respiracao + tremulacao sutil
  if (screenGlowLight) {
    screenGlowLight.intensity = 1.05 + Math.sin(t * 2.2) * 0.12 + Math.sin(t * 13.7) * 0.05;
  }

  // physical button press: quick dip and return along the deck normal
  for (const m of pressables) {
    const p = m.userData.press || 0;
    if (p > 0) {
      m.userData.press = Math.max(0, p - dt * 5);
      const s = cabinetModel ? cabinetModel.scale.x : 1;
      const depth = Math.sin(Math.min(1, 1 - m.userData.press) * Math.PI) * (10 / s);
      m.position.copy(btnRest.get(m)).addScaledVector(pressDirLocal, depth);
      const lf = lampFor.get(m);
      if (lf) {
        lf.lamp.position.copy(lf.rest).addScaledVector(pressDirLocal, depth);
        if (lf.label) lf.label.position.copy(lf.labelRest).addScaledVector(pressDirLocal, depth * cabinetModel.scale.x);
      }
    }
  }

  // flash das lampadas: forte no clique, decaindo ao repouso fraco
  for (const lf of lampFor.values()) {
    const u = lf.lamp.userData;
    if (u.flash > 0) {
      u.flash = Math.max(0, u.flash - dt * 1.5);
      lf.lamp.material.emissiveIntensity = lf.base + (5.6 - lf.base) * u.flash;
    }
  }

  // joystick: segue o arrasto, e sozinho ganha vida — deriva lenta em
  // repouso, rodopio no frenesi do PINOMIZE
  if (joyPivot) {
    let tx = joyTilt.x;
    let ty = joyTilt.y;
    if (!joyDrag && !REDUCED && (!intro || intro.done)) {
      if (t < joyFrenzyUntil) {
        tx += Math.sin(t * 4.6) * 0.3;
        ty += Math.cos(t * 5.3) * 0.3;
      } else {
        tx += Math.sin(t * 0.7) * 0.05 + Math.sin(t * 1.9) * 0.025;
        ty += Math.cos(t * 0.55) * 0.055 + Math.sin(t * 1.3) * 0.02;
      }
    }
    joyPivot.rotation.x += (tx - joyPivot.rotation.x) * 0.25;
    joyPivot.rotation.z += (-ty - joyPivot.rotation.z) * 0.25;
  }

  for (const m of flickering) {
    const on = t >= (m.userData.powerAt ?? 0);
    if (!on) {
      m.material.opacity = 0;
      continue;
    }
    if (REDUCED) {
      m.material.opacity = m.userData.base;
      continue;
    }
    const s = m.userData.seed;
    const age = t - m.userData.powerAt;
    // surto de ligar: pisca forte no primeiro meio segundo
    const igniting = age < 0.5 ? (Math.sin(age * 40 + s) > -0.2 ? 1 : 0.15) : 1;
    const flick = Math.sin(t * 9 + s) * Math.sin(t * 23 + s * 3);
    m.material.opacity = (m.userData.base - (flick > 0.93 ? 0.5 : 0) - 0.06 * Math.sin(t * 2 + s)) * igniting;
    m.material.transparent = true;
  }

  renderer.render(scene, camera);
  cssRenderer.render(cssScene, camera);
}

addEventListener('resize', () => {
  camera.aspect = innerWidth / innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(innerWidth, innerHeight);
  cssRenderer.setSize(innerWidth, innerHeight);

  // re-enquadra ao girar o telefone / redimensionar
  if (intro) {
    const p = playerPose();
    intro.finalPos.copy(p.pos);
    intro.frameCenter.copy(p.target);
    if (intro.done) {
      camera.position.copy(p.pos);
      controls.target.copy(p.target);
    }
  }
});

init();
