// ============================================================
// PINORATOR ARCADE 3D — Blender-built cabinet + live HTML screen.
// pinocab.glb is generated by make_arcade.py (Blender headless);
// its 'monitor' plane hosts the CRT UI as a CSS3DObject, and the
// art_* planes are runtime texture slots. script.js untouched.
// ============================================================
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { CSS3DRenderer, CSS3DObject } from 'three/addons/renderers/CSS3DRenderer.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

// ================= SUAS TEXTURAS AQUI =================
// Coloque imagens (png/jpg) no projeto e aponte o caminho.
// Deixe null para usar o visual padrao ($PINO branco/amarelo).
const TEXTURES = {
  side: null,     // arte lateral (os dois lados)     ex.: 'images/arcade/side.png'
  marquee: null,  // letreiro do topo                 ex.: 'images/arcade/marquee.png'
  front: null,    // painel frontal (coin door)       ex.: 'images/arcade/front.png'
  deck: null,     // superficie do painel de controle ex.: 'images/arcade/deck.png'
};
// ======================================================

const ROOM_COLOR = 0x05030c;
// world width of the monitor glass in px; the .crt element is authored
// wider (880px, see arcade3d.css) and shrunk to fit — free supersampling
const UI_WIDTH = 640;
const REDUCED = matchMedia('(prefers-reduced-motion: reduce)').matches;

const webglRoot = document.getElementById('webgl-root');
const cssRoot = document.getElementById('css3d-root');
const crtEl = document.querySelector('.crt');

// the action buttons join the screen UI, like an in-game menu
crtEl.querySelector('.customization').after(document.getElementById('buttons-container'));

const scene = new THREE.Scene();
scene.background = new THREE.Color(ROOM_COLOR);
scene.fog = new THREE.Fog(ROOM_COLOR, 2200, 5200);

const cssScene = new THREE.Scene();

const camera = new THREE.PerspectiveCamera(40, innerWidth / innerHeight, 1, 14000);

const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.setSize(innerWidth, innerHeight);
webglRoot.appendChild(renderer.domElement);

const cssRenderer = new CSS3DRenderer();
cssRenderer.setSize(innerWidth, innerHeight);
cssRoot.appendChild(cssRenderer.domElement);

const screenObj = new CSS3DObject(crtEl);
cssScene.add(screenObj);

const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.06;
controls.enablePan = false;
controls.minAzimuthAngle = -0.6;
controls.maxAzimuthAngle = 0.6;
controls.minPolarAngle = Math.PI / 2 - 0.6;
controls.maxPolarAngle = Math.PI / 2 + 0.15;

// ---------- texture helpers ----------
const texLoader = new THREE.TextureLoader();

function imageTexture(path) {
  const t = texLoader.load(path);
  t.colorSpace = THREE.SRGBColorSpace;
  t.anisotropy = 4;
  return t;
}

function neonTexture(text, color, px = 90, bg = '#160d2a') {
  const c = document.createElement('canvas');
  c.width = 1024; c.height = 256;
  const x = c.getContext('2d');
  if (bg) {
    x.fillStyle = bg;
    x.fillRect(0, 0, 1024, 256);
  }
  x.font = `${px}px "Press Start 2P", monospace`;
  x.textAlign = 'center';
  x.textBaseline = 'middle';
  x.shadowColor = color;
  x.shadowBlur = 42;
  x.fillStyle = color;
  for (let i = 0; i < 4; i++) x.fillText(text, 512, 134);
  const t = new THREE.CanvasTexture(c);
  t.colorSpace = THREE.SRGBColorSpace;
  return t;
}

// ---------- room ----------
const flickering = [];

function addSign(text, color, x, y, z, ry = 0, scale = 1) {
  const mat = new THREE.MeshBasicMaterial({
    map: neonTexture(text, color, 90, null),
    transparent: true,
    depthWrite: false,
    fog: false,
  });
  const m = new THREE.Mesh(new THREE.PlaneGeometry(760 * scale, 190 * scale), mat);
  m.position.set(x, y, z);
  m.rotation.y = ry;
  m.userData.base = 0.8 + Math.random() * 0.2;
  m.userData.seed = Math.random() * 100;
  flickering.push(m);
  scene.add(m);
}

function buildRoom(floorY) {
  const floor = new THREE.Mesh(
    new THREE.PlaneGeometry(10000, 10000),
    new THREE.MeshStandardMaterial({ color: 0x0a0616, roughness: 0.35, metalness: 0.55 })
  );
  floor.rotation.x = -Math.PI / 2;
  floor.position.y = floorY;
  scene.add(floor);

  const grid = new THREE.GridHelper(10000, 100, 0x2ee6ff, 0x2ee6ff);
  grid.material.transparent = true;
  grid.material.opacity = 0.16;
  grid.position.y = floorY + 2;
  scene.add(grid);

  const backWall = new THREE.Mesh(
    new THREE.PlaneGeometry(10000, 4600),
    new THREE.MeshStandardMaterial({ color: 0x0b0618, roughness: 0.95 })
  );
  backWall.position.set(0, floorY + 2300, -2600);
  scene.add(backWall);

  addSign('$PINO', '#f7ca16', -1050, 700, -2500, 0.12, 1.5);
  addSign('WAGMI', '#2ee6ff', 1100, 850, -2520, -0.1, 1);
  addSign('DEGEN', '#39ff6a', 1250, 180, -2540, -0.06, 0.9);
  addSign('HODL', '#ff6300', -1250, 90, -2540, 0.08, 0.9);
  addSign('GM', '#ff3ea5', -1650, 420, -1750, 0.5, 0.8);
  addSign('TO THE MOON', '#8f7bd8', 1700, 470, -1650, -0.5, 0.7);
}

function buildLights(h) {
  scene.add(new THREE.AmbientLight(0x9990cc, 0.9));

  const key = new THREE.DirectionalLight(0xfff2d8, 1.7);
  key.position.set(400, 700, 900);
  scene.add(key);

  // frontal fill so the black column reads instead of vanishing
  const fill = new THREE.PointLight(0xffffff, 0.45, 0, 0);
  fill.position.set(0, -h * 0.15, 900);
  scene.add(fill);

  const screenGlow = new THREE.PointLight(0x39ff6a, 0.8, 0, 0);
  screenGlow.position.set(0, h * 0.1, 300);
  scene.add(screenGlow);

  const magenta = new THREE.PointLight(0xff3ea5, 0.5, 0, 0);
  magenta.position.set(-1400, 300, -1000);
  scene.add(magenta);

  const cyan = new THREE.PointLight(0x2ee6ff, 0.5, 0, 0);
  cyan.position.set(1400, 300, -1000);
  scene.add(cyan);
}

// ---------- the machine, generated in Blender ----------
async function loadCabinet() {
  const gltf = await new GLTFLoader().loadAsync('pinocab.glb');
  const model = gltf.scene;
  scene.add(model);

  // runtime texture slots: user image, default art, or hidden
  const artMap = {
    art_side_l: TEXTURES.side,
    art_side_r: TEXTURES.side,
    art_marquee: TEXTURES.marquee,
    art_front: TEXTURES.front,
    art_deck: TEXTURES.deck,
  };
  model.traverse(o => {
    if (!o.isMesh || !(o.name in artMap)) return;
    const path = artMap[o.name];
    if (path) {
      o.material = new THREE.MeshBasicMaterial({ map: imageTexture(path), transparent: true });
    } else if (o.name === 'art_marquee') {
      o.material = new THREE.MeshBasicMaterial({ map: neonTexture('PINORATOR', '#f7ca16', 96) });
      o.userData.base = 1;
      o.userData.seed = 7;
      flickering.push(o);
    } else {
      o.visible = false;
    }
  });

  const monitor = model.getObjectByName('monitor');

  // scale the machine so the monitor glass is UI_WIDTH world px wide
  model.updateMatrixWorld(true);
  let box = new THREE.Box3().setFromObject(monitor);
  let size = box.getSize(new THREE.Vector3());
  model.scale.setScalar(UI_WIDTH / size.x);
  model.updateMatrixWorld(true);

  // center the monitor at the origin
  box = new THREE.Box3().setFromObject(monitor);
  size = box.getSize(new THREE.Vector3());
  model.position.sub(box.getCenter(new THREE.Vector3()));
  model.updateMatrixWorld(true);

  // orient the UI to the monitor's tilt: the surface rises from its
  // front-bottom edge (max z) to its back-top edge (min z)
  const upDir = new THREE.Vector3(0, size.y, -size.z).normalize();
  const rightDir = new THREE.Vector3(1, 0, 0);
  const normalDir = new THREE.Vector3().crossVectors(rightDir, upDir).normalize();
  screenObj.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(rightDir, upDir, normalDir));
  screenObj.position.copy(normalDir).multiplyScalar(8);

  return { model, monLen: Math.hypot(size.y, size.z) };
}

// ---------- physical controls: real buttons + working joystick ----------
const DOM_BTN = { btn_0: 'generate-btn', btn_1: 'default-btn', btn_2: 'download-btn' };
const BTN_LABELS = {
  btn_0: ['PINOMIZE', '#f7ca16'],
  btn_1: ['RESET', '#ff3ea5'],
  btn_2: ['DOWNLOAD', '#39ff6a'],
};
const TAB_IDS = ['tab-front', 'tab-hats', 'tab-eyes', 'tab-clothes', 'tab-mouth', 'tab-cores', 'tab-based'];
const TAB_OPTS = {
  'tab-front': 'front', 'tab-hats': 'hats', 'tab-eyes': 'glasses',
  'tab-clothes': 'clothes', 'tab-mouth': 'mouth', 'tab-cores': 'cores', 'tab-based': 'based',
};
const traitIndex = {};
const pressables = [];
const btnRest = new Map();
let cabinetModel = null;
let pressDirLocal = new THREE.Vector3(0, 0, -1);
let joyPivot = null;
const joyTilt = new THREE.Vector2(); // target x (frente/tras), y (lados)
let joyDrag = null;

function labelTexture(text, color) {
  const c = document.createElement('canvas');
  c.width = 512; c.height = 112;
  const x = c.getContext('2d');
  x.font = '44px "Press Start 2P", monospace';
  x.textAlign = 'center';
  x.textBaseline = 'middle';
  x.shadowColor = color;
  x.shadowBlur = 14;
  x.fillStyle = color;
  for (let i = 0; i < 3; i++) x.fillText(text, 256, 58);
  const t = new THREE.CanvasTexture(c);
  t.colorSpace = THREE.SRGBColorSpace;
  return t;
}

function activeTabId() {
  return TAB_IDS.find(id => document.getElementById(id).checked);
}

function switchTab(dir) {
  const i = TAB_IDS.indexOf(activeTabId());
  document.getElementById(TAB_IDS[(i + dir + TAB_IDS.length) % TAB_IDS.length]).click();
}

function navTrait(dir) {
  const cls = TAB_OPTS[activeTabId()];
  const btns = [...document.querySelectorAll(`.options.${cls} button`)];
  if (!btns.length) return;
  const next = ((traitIndex[cls] ?? 0) + dir + btns.length) % btns.length;
  traitIndex[cls] = next;
  btns[next].click();
  btns[next].scrollIntoView({ behavior: 'smooth', inline: 'center', block: 'nearest' });
  btns.forEach(b => b.classList.remove('joy-selected'));
  btns[next].classList.add('joy-selected');
}

function pressButton(name) {
  const mesh = cabinetModel && cabinetModel.getObjectByName(name);
  if (mesh) mesh.userData.press = 1;
  if (name !== 'btn_2') {
    const av = document.querySelector('.avatar-display');
    av.classList.add('glitching');
    setTimeout(() => av.classList.remove('glitching'), 400);
  }
  setTimeout(() => document.getElementById(DOM_BTN[name]).click(), 70);
}

function setupMachineControls(model) {
  cabinetModel = model;

  for (const name of Object.keys(DOM_BTN)) {
    const m = model.getObjectByName(name);
    if (!m) continue;
    pressables.push(m);
    btnRest.set(m, m.position.clone());
  }

  // deck orientation straight from the blueprint: surface drops ~21.8
  // degrees toward the player (world +Z forward, +Y up)
  const DECK_ANG = Math.atan2(0.07, 0.175);
  const outNormal = new THREE.Vector3(0, Math.cos(DECK_ANG), Math.sin(DECK_ANG));
  const downSlope = new THREE.Vector3(0, -Math.sin(DECK_ANG), Math.cos(DECK_ANG));
  const labelQuat = new THREE.Quaternion().setFromRotationMatrix(
    new THREE.Matrix4().makeBasis(new THREE.Vector3(1, 0, 0), downSlope.clone().negate(), outNormal)
  );
  // model root carries no rotation, so world dir == local dir
  pressDirLocal = outNormal.clone().multiplyScalar(-1);

  // engraved labels under the buttons
  for (const [name, [text, color]] of Object.entries(BTN_LABELS)) {
    const m = model.getObjectByName(name);
    if (!m) continue;
    const p = new THREE.Vector3();
    m.getWorldPosition(p);
    const label = new THREE.Mesh(
      new THREE.PlaneGeometry(80, 18),
      new THREE.MeshBasicMaterial({ map: labelTexture(text, color), transparent: true, fog: false })
    );
    label.quaternion.copy(labelQuat);
    label.position.copy(p).addScaledVector(downSlope, 40).addScaledVector(outNormal, 4);
    scene.add(label);
  }

  // joystick pivot so stick + ball tilt around the base
  const base = model.getObjectByName('joy_base');
  const stick = model.getObjectByName('joy_stick');
  const ball = model.getObjectByName('joy_ball');
  joyPivot = new THREE.Group();
  base.parent.add(joyPivot);
  joyPivot.position.copy(base.position);
  joyPivot.attach(stick);
  joyPivot.attach(ball);

  const raycaster = new THREE.Raycaster();
  const pointer = new THREE.Vector2();

  function pick(ev, objects) {
    const r = renderer.domElement.getBoundingClientRect();
    pointer.set(((ev.clientX - r.left) / r.width) * 2 - 1, -((ev.clientY - r.top) / r.height) * 2 + 1);
    raycaster.setFromCamera(pointer, camera);
    return raycaster.intersectObjects(objects, false)[0];
  }

  renderer.domElement.addEventListener('pointerdown', ev => {
    if (pick(ev, pressables)) {
      const hit = pick(ev, pressables);
      pressButton(hit.object.name);
      controls.enabled = false;
      return;
    }
    if (pick(ev, [ball, stick, base])) {
      joyDrag = { x: ev.clientX, y: ev.clientY, fired: false };
      controls.enabled = false;
    }
  });

  addEventListener('pointermove', ev => {
    if (!joyDrag) return;
    const dx = ev.clientX - joyDrag.x;
    const dy = ev.clientY - joyDrag.y;
    joyTilt.set(
      THREE.MathUtils.clamp(dy * 0.008, -0.38, 0.38),
      THREE.MathUtils.clamp(dx * 0.008, -0.38, 0.38)
    );
    const TH = 30;
    if (!joyDrag.fired) {
      if (Math.abs(dx) > TH && Math.abs(dx) >= Math.abs(dy)) {
        navTrait(dx > 0 ? 1 : -1);
        joyDrag.fired = true;
      } else if (Math.abs(dy) > TH) {
        switchTab(dy > 0 ? 1 : -1);
        joyDrag.fired = true;
      }
    } else if (Math.abs(dx) < TH * 0.4 && Math.abs(dy) < TH * 0.4) {
      joyDrag.fired = false; // voltar ao centro rearma o gesto
    }
  });

  addEventListener('pointerup', () => {
    if (!joyDrag && controls.enabled === false) controls.enabled = true;
    joyDrag = null;
    joyTilt.set(0, 0);
    controls.enabled = true;
  });

  // keyboard mirrors the joystick: arrows navigate, Enter pinomizes
  addEventListener('keydown', ev => {
    switch (ev.key) {
      case 'ArrowLeft': navTrait(-1); joyKick(0, -1); break;
      case 'ArrowRight': navTrait(1); joyKick(0, 1); break;
      case 'ArrowUp': switchTab(-1); joyKick(-1, 0); break;
      case 'ArrowDown': switchTab(1); joyKick(1, 0); break;
      case 'Enter': pressButton('btn_0'); break;
      default: return;
    }
    ev.preventDefault();
  });
}

let joyKickTimer = null;
function joyKick(x, y) {
  joyTilt.set(x * 0.3, y * 0.3);
  clearTimeout(joyKickTimer);
  joyKickTimer = setTimeout(() => joyTilt.set(0, 0), 180);
}

// ---------- boot ----------
async function init() {
  try {
    await Promise.race([
      Promise.all([document.fonts.load('16px "Press Start 2P"'), document.fonts.ready]),
      new Promise(r => setTimeout(r, 2500)),
    ]);
  } catch { /* fonts are cosmetic; the scene still builds */ }

  const { model, monLen } = await loadCabinet();

  // first CSS render mounts the element; then it can be measured
  cssRenderer.render(cssScene, camera);
  document.querySelector('.cabinet').style.display = 'none';
  // fill the whole glass: per-axis scale (the UI layout is tuned to the
  // glass aspect, so the residual stretch is a few percent, invisible)
  const uiW = crtEl.offsetWidth || UI_WIDTH;
  const uiH = crtEl.offsetHeight || 900;
  screenObj.scale.set(UI_WIDTH / uiW, monLen / uiH, 1);

  const mBox = new THREE.Box3().setFromObject(model);
  const mSize = mBox.getSize(new THREE.Vector3());

  buildRoom(mBox.min.y);
  buildLights(mSize.y);

  // player's point of view: standing at the machine, looking down
  const dist = (mSize.y / 2) / Math.tan(THREE.MathUtils.degToRad(camera.fov / 2)) * 1.15;
  camera.position.set(0, dist * 0.42, dist * 0.95);
  controls.target.set(0, 0, 0);
  controls.minDistance = dist * 0.35;
  controls.maxDistance = dist * 1.6;
  controls.update();

  setupMachineControls(model);

  renderer.setAnimationLoop(tick);
  tick(); // paint the first frame synchronously, even in a throttled tab
}

const clock = new THREE.Clock();

function tick() {
  const dt = clock.getDelta();
  const t = clock.elapsedTime;
  controls.update();

  // physical button press: quick dip and return along the deck normal
  for (const m of pressables) {
    const p = m.userData.press || 0;
    if (p > 0) {
      m.userData.press = Math.max(0, p - dt * 5);
      const s = cabinetModel ? cabinetModel.scale.x : 1;
      const depth = Math.sin(Math.min(1, 1 - m.userData.press) * Math.PI) * (10 / s);
      m.position.copy(btnRest.get(m)).addScaledVector(pressDirLocal, depth);
    }
  }

  // joystick springs toward the drag direction
  if (joyPivot) {
    joyPivot.rotation.x += (joyTilt.x - joyPivot.rotation.x) * 0.3;
    joyPivot.rotation.z += (-joyTilt.y - joyPivot.rotation.z) * 0.3;
  }

  if (!REDUCED) {
    for (const m of flickering) {
      const s = m.userData.seed;
      const flick = Math.sin(t * 9 + s) * Math.sin(t * 23 + s * 3);
      m.material.opacity = m.userData.base - (flick > 0.93 ? 0.5 : 0) - 0.06 * Math.sin(t * 2 + s);
      m.material.transparent = true;
    }
  }

  renderer.render(scene, camera);
  cssRenderer.render(cssScene, camera);
}

addEventListener('resize', () => {
  camera.aspect = innerWidth / innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(innerWidth, innerHeight);
  cssRenderer.setSize(innerWidth, innerHeight);
});

init();
